/**
 * Decision Event Pipeline — pure capture core.
 *
 * The mapping from a raw Claude Code hook event onto a Move envelope, and
 * the policy for when a capture should trigger a background drain. Kept
 * free of I/O so the wire mapping can be unit-pinned: a silent rename of a
 * Claude Code field (e.g. hook_event_name) would otherwise zero the
 * pipeline invisibly.
 */
import { createHash, randomUUID } from "node:crypto";
import { platform } from "node:os";
import { isValidRepoSyncId } from "../lib/activation.js";
import type { RepositoryContext } from "../lib/git.js";
import { isCanonicalWorkspaceId } from "../lib/workspace-id.js";
import {
  AGENT_ENVELOPE_VERSION,
  type AgentProducer,
  ENVELOPE_VERSION,
  type Move,
  type ToolOutcome,
} from "../protocol/move.js";
import type { Agent } from "./agent.js";

const CORRELATED_TOOL_EVENTS = new Set([
  "PostToolUse",
  "PostToolUseFailure",
  "post_tool_call",
  "post_approval_response",
]);

export function postToolInvocationId(
  parsed: Record<string, unknown>,
  agent: Agent,
): string | undefined {
  if (
    typeof parsed.hook_event_name !== "string" ||
    !CORRELATED_TOOL_EVENTS.has(parsed.hook_event_name)
  ) {
    return undefined;
  }
  const raw =
    agent === "hermes"
      ? (parsed.extra as { tool_call_id?: unknown } | undefined)?.tool_call_id
      : parsed.tool_use_id;
  return typeof raw === "string" && raw.length > 0 ? raw : undefined;
}

function lowerString(value: unknown): string | undefined {
  return typeof value === "string" ? value.toLowerCase() : undefined;
}

/**
 * Normalize only outcome claims each host's hook contract can actually make.
 * In particular, Codex's post hook says a result returned but does not certify
 * success, and a Hermes approval is not a tool result.
 */
export function toolOutcomeFor(
  parsed: Record<string, unknown>,
  agent: Agent,
): ToolOutcome | undefined {
  const event = parsed.hook_event_name;
  if (agent === "claude_code") {
    if (event === "PostToolUseFailure") {
      return parsed.is_interrupt === true ? "interrupted" : "failed";
    }
    return event === "PostToolUse" ? "succeeded" : undefined;
  }
  if (agent === "codex") {
    return event === "PostToolUse" ? "returned" : undefined;
  }

  const extra = parsed.extra as Record<string, unknown> | undefined;
  if (event === "post_approval_response") {
    const choice = lowerString(extra?.choice);
    return (choice === "deny" || choice === "smart_deny" || choice === "timeout") &&
      postToolInvocationId(parsed, agent)
      ? "prevented"
      : undefined;
  }
  if (event !== "PostToolUse" && event !== "post_tool_call") {
    return undefined;
  }
  const status = lowerString(extra?.status);
  if (status === "ok" || status === "success") {
    return "succeeded";
  }
  if (status === "error" || status === "timeout") {
    return "failed";
  }
  if (status === "cancelled") {
    return "interrupted";
  }
  if (status === "blocked") {
    return "prevented";
  }
  // Hermes post-tool delivery proves a callback occurred, but an absent or
  // newer status cannot be promoted to success (Codex alone uses "returned").
  return "unknown";
}

export function toMove(
  parsed: Record<string, unknown>,
  cliVersion: string,
  agent: Agent = "claude_code",
  workspaceId?: string,
  repository?: RepositoryContext | null,
  invocationId?: string,
): Move {
  const sessionId = (parsed.session_id as string | undefined) ?? "";
  const eventType = (parsed.hook_event_name as string | undefined) ?? "unknown";
  const toolOutcome = toolOutcomeFor(parsed, agent);
  const moveId =
    CORRELATED_TOOL_EVENTS.has(eventType) && sessionId && invocationId
      ? `posttool:v1:${createHash("sha256")
          .update(JSON.stringify([agent, sessionId, eventType, invocationId]))
          .digest("hex")}`
      : randomUUID();
  return {
    moveId,
    capturedAt: Date.now(),
    sessionId,
    eventType,
    payload: parsed,
    env: {
      cwd: (parsed.cwd as string | undefined) ?? process.cwd(),
      cliVersion,
      osPlatform: platform(),
      ...(repository
        ? {
            repoRoot: repository.repoRoot,
            repoKey: repository.repoKey,
            gitRoot: repository.repoRoot,
            repoFullName: repository.repoFullName,
            repoSyncId: repository.repoSyncId,
          }
        : {}),
      ...(workspaceId ? { workspaceId } : {}),
    },
    envelopeVersion: AGENT_ENVELOPE_VERSION,
    producer: agent,
    ...(invocationId ? { invocationId } : {}),
    ...(toolOutcome ? { toolOutcome } : {}),
  };
}

export type CommitInfo = {
  sha: string;
  parentSha?: string;
  branch?: string;
  files: string[];
  filesComplete: boolean;
};

export type CommitAttribution = {
  sessionId: string;
  producer: Exclude<AgentProducer, "hermes">;
};

export type CommitMoveContext = {
  repository?: RepositoryContext | null;
  repoFullName?: string;
  /** Existing local `prim.repoSyncId`; never generated by the hook. */
  repoSyncId?: string;
  workspaceId?: string;
  attribution?: CommitAttribution;
  /** Hook-fire time preserved by the synchronous post-commit launcher. */
  capturedAt?: number;
};

export type RewriteSource = "amend" | "rebase";

export type RewritePair = {
  oldSha: string;
  newSha: string;
};

export type RewriteInfo = {
  source: RewriteSource;
  pairs: RewritePair[];
  branch?: string;
};

export type RewriteMoveContext = {
  repository?: RepositoryContext | null;
  repoFullName?: string;
  /** Existing local `prim.repoSyncId`; never generated by the hook. */
  repoSyncId?: string;
  workspaceId?: string;
  capturedAt?: number;
};

/** Wire cap shared with the server's inline git.rewrite validator. */
export const MAX_REWRITE_PAIRS_PER_MOVE = 40;
/** Defensive per-hook cap before deterministic chunking. */
export const MAX_REWRITE_PAIRS_PER_HOOK = 2_000;
const FULL_SHA_RE = /^(?:[0-9a-f]{40}|[0-9a-f]{64})$/u;

const MAX_CLASSIFIER_ID_CHARS = 256;
// Keep client hints within the durable classifier's identifier contract.
// biome-ignore lint/suspicious/noControlCharactersInRegex: classifier hints reject controls and surrogate code units
const INVALID_CLASSIFIER_ID_RE = /[\u0000-\u001f\u007f\uD800-\uDFFF]/u;

function validSessionHint(value: string | undefined): value is string {
  return (
    typeof value === "string" &&
    value.trim().length > 0 &&
    value === value.trim() &&
    value.length <= MAX_CLASSIFIER_ID_CHARS &&
    !INVALID_CLASSIFIER_ID_RE.test(value)
  );
}

/**
 * Attribute a commit only when one supported agent exported exactly one valid
 * session hint and this worktree has a valid local identity. All other cases
 * deliberately stay sessionless for server-side evidence correlation.
 */
export function commitAttributionFromEnvironment(
  env: NodeJS.ProcessEnv,
  workspaceId: string | undefined,
): CommitAttribution | undefined {
  // Hermes commits are always correlated from server-stamped edit evidence.
  // Fail closed if its runtime inherited another agent's session variable.
  if (env.HERMES_INTERACTIVE) return undefined;
  if (!workspaceId || !isCanonicalWorkspaceId(workspaceId)) return undefined;
  const candidates = [
    validSessionHint(env.CLAUDE_CODE_SESSION_ID)
      ? { sessionId: env.CLAUDE_CODE_SESSION_ID, producer: "claude_code" as const }
      : undefined,
    validSessionHint(env.CODEX_THREAD_ID)
      ? { sessionId: env.CODEX_THREAD_ID, producer: "codex" as const }
      : undefined,
  ].filter((candidate): candidate is CommitAttribution => candidate !== undefined);
  return candidates.length === 1 ? candidates[0] : undefined;
}

/**
 * Build the Move a git post-commit hook emits. The commit bounds a
 * classification window server-side. When repository and worktree identities
 * are valid, its deterministic `commit:v2:<hash>` moveId makes a double-fired
 * or replayed hook idempotent without colliding with the same SHA in another
 * tenant or checkout. An identity-less fallback is random rather than global.
 * eventType "git.commit" matches the server's
 * GIT_COMMIT_EVENT — a cross-repo wire contract. No producer is stamped: a
 * git hook fires for every commit regardless of which agent (if any) was
 * running, and the decision's agent attribution comes from the session's
 * own moves, not the commit envelope. A uniquely attributable Claude/Codex
 * commit uses V3; human, GUI, Hermes, missing, or conflicting hints remain V1.
 */
export function toCommitMove(
  commit: CommitInfo,
  cliVersion: string,
  cwd: string,
  context: CommitMoveContext = {},
): Move {
  const { repository, repoFullName, repoSyncId, workspaceId, attribution, capturedAt } = context;
  const validatedRepoSyncId = isValidRepoSyncId(repoSyncId) ? repoSyncId : undefined;
  const validatedWorkspaceId =
    workspaceId && isCanonicalWorkspaceId(workspaceId) ? workspaceId : undefined;
  const validatedAttribution = validatedWorkspaceId ? attribution : undefined;
  const validatedCapturedAt =
    typeof capturedAt === "number" && Number.isSafeInteger(capturedAt) && capturedAt > 0
      ? capturedAt
      : Date.now();
  const fullSha = /^(?:[0-9a-f]{40}|[0-9a-f]{64})$/u.test(commit.sha);
  const moveId =
    validatedRepoSyncId && validatedWorkspaceId && fullSha
      ? `commit:v2:${createHash("sha256")
          .update(
            JSON.stringify(["commit:v2", validatedRepoSyncId, validatedWorkspaceId, commit.sha]),
          )
          .digest("hex")}`
      : `commit:v2:unscoped:${randomUUID()}`;
  const base = {
    moveId,
    capturedAt: validatedCapturedAt,
    sessionId: validatedAttribution?.sessionId ?? "",
    eventType: "git.commit",
    payload: {
      kind: "git.commit",
      sha: commit.sha,
      parentSha: commit.parentSha,
      branch: commit.branch,
      changedFiles: commit.files,
      changedFilesComplete: commit.filesComplete,
    },
    env: {
      cwd,
      cliVersion,
      osPlatform: platform(),
      ...(repository
        ? {
            repoRoot: repository.repoRoot,
            repoKey: repository.repoKey,
            gitRoot: repository.repoRoot,
          }
        : {}),
      ...(repoFullName ? { repoFullName } : {}),
      ...(validatedRepoSyncId ? { repoSyncId: validatedRepoSyncId } : {}),
      ...(validatedWorkspaceId ? { workspaceId: validatedWorkspaceId } : {}),
    },
  };
  return validatedAttribution
    ? {
        ...base,
        envelopeVersion: AGENT_ENVELOPE_VERSION,
        producer: validatedAttribution.producer,
      }
    : { ...base, envelopeVersion: ENVELOPE_VERSION };
}

/**
 * Canonicalize Git's rewrite mapping before chunking. A malformed entry rejects
 * the invocation; valid pairs are lowercase, self-pairs are dropped, exact
 * duplicates collapse, and sorting makes truncation/chunk boundaries stable.
 */
export function canonicalRewritePairs(pairs: RewritePair[]): RewritePair[] | null {
  const unique = new Map<string, RewritePair>();
  for (const pair of pairs) {
    const oldSha = pair.oldSha.toLowerCase();
    const newSha = pair.newSha.toLowerCase();
    if (!FULL_SHA_RE.test(oldSha) || !FULL_SHA_RE.test(newSha)) return null;
    if (oldSha === newSha) continue;
    unique.set(`${oldSha}\0${newSha}`, { oldSha, newSha });
  }
  return [...unique.values()]
    .sort((left, right) => {
      const leftKey = `${left.oldSha}\0${left.newSha}`;
      const rightKey = `${right.oldSha}\0${right.newSha}`;
      return leftKey < rightKey ? -1 : leftKey > rightKey ? 1 : 0;
    })
    .slice(0, MAX_REWRITE_PAIRS_PER_HOOK);
}

/**
 * Build deterministic V1 git.rewrite Moves, one per 40-pair inline chunk.
 * Rewrites require both the server-issued repository binding and stable local
 * worktree identity because both scope the immutable move id.
 */
export function toRewriteMove(
  rewrite: RewriteInfo,
  cliVersion: string,
  cwd: string,
  context: RewriteMoveContext,
): Move[] {
  const { repository, repoFullName, repoSyncId, workspaceId, capturedAt } = context;
  if (
    (rewrite.source !== "amend" && rewrite.source !== "rebase") ||
    !isValidRepoSyncId(repoSyncId) ||
    !workspaceId ||
    !isCanonicalWorkspaceId(workspaceId)
  ) {
    return [];
  }
  const pairs = canonicalRewritePairs(rewrite.pairs);
  if (!pairs || pairs.length === 0) return [];
  const branch =
    rewrite.branch &&
    rewrite.branch === rewrite.branch.trim() &&
    ![...rewrite.branch].some((char) => char < " " || char === "\u007f")
      ? rewrite.branch
      : undefined;
  const observedAt =
    typeof capturedAt === "number" && Number.isSafeInteger(capturedAt) && capturedAt > 0
      ? capturedAt
      : Date.now();
  const moves: Move[] = [];
  for (let offset = 0; offset < pairs.length; offset += MAX_REWRITE_PAIRS_PER_MOVE) {
    const sortedPairs = pairs.slice(offset, offset + MAX_REWRITE_PAIRS_PER_MOVE);
    const moveId = `rewrite:v1:${createHash("sha256")
      .update(JSON.stringify(["rewrite:v1", repoSyncId, workspaceId, rewrite.source, sortedPairs]))
      .digest("hex")}`;
    moves.push({
      moveId,
      capturedAt: observedAt,
      sessionId: "",
      eventType: "git.rewrite",
      payload: {
        kind: "git.rewrite",
        source: rewrite.source,
        pairs: sortedPairs,
        ...(branch ? { branch } : {}),
      },
      env: {
        cwd,
        cliVersion,
        osPlatform: platform(),
        ...(repository
          ? {
              repoRoot: repository.repoRoot,
              repoKey: repository.repoKey,
              gitRoot: repository.repoRoot,
            }
          : {}),
        ...(repoFullName ? { repoFullName } : {}),
        repoSyncId,
        workspaceId,
      },
      envelopeVersion: ENVELOPE_VERSION,
    });
  }
  return moves;
}

/**
 * Session-terminal events at which the hook kicks a best-effort background
 * drain, so a session's moves reach the server promptly instead of waiting
 * for the next interactive `prim` invocation.
 */
export function shouldFlushAfter(eventType: string): boolean {
  return eventType === "SessionEnd";
}
