/**
 * Decision Event Pipeline — pure capture core.
 *
 * The mapping from a raw Claude Code hook event onto a Move envelope, and
 * the policy for when a capture should trigger a background drain. Kept
 * free of I/O so the wire mapping can be unit-pinned: a silent rename of a
 * Claude Code field (e.g. hook_event_name) would otherwise zero the
 * pipeline invisibly.
 */
import { createHash, randomUUID } from "node:crypto";
import { platform } from "node:os";
import { isValidRepoSyncId } from "../lib/activation.js";
import type { RepositoryContext } from "../lib/git.js";
import { isCanonicalWorkspaceId } from "../lib/workspace-id.js";
import {
  AGENT_ENVELOPE_VERSION,
  type AgentProducer,
  ENVELOPE_VERSION,
  type Move,
} from "../protocol/move.js";
import type { Agent } from "./agent.js";

export function postToolInvocationId(
  parsed: Record<string, unknown>,
  agent: Agent,
): string | undefined {
  if (parsed.hook_event_name !== "PostToolUse") return undefined;
  const raw =
    agent === "hermes"
      ? (parsed.extra as { tool_call_id?: unknown } | undefined)?.tool_call_id
      : parsed.tool_use_id;
  return typeof raw === "string" && raw.length > 0 ? raw : undefined;
}

export function toMove(
  parsed: Record<string, unknown>,
  cliVersion: string,
  agent: Agent = "claude_code",
  workspaceId?: string,
  repository?: RepositoryContext | null,
  invocationId?: string,
): Move {
  const sessionId = (parsed.session_id as string | undefined) ?? "";
  const eventType = (parsed.hook_event_name as string | undefined) ?? "unknown";
  const moveId =
    eventType === "PostToolUse" && sessionId && invocationId
      ? `posttool:v1:${createHash("sha256")
          .update(JSON.stringify([agent, sessionId, eventType, invocationId]))
          .digest("hex")}`
      : randomUUID();
  return {
    moveId,
    capturedAt: Date.now(),
    sessionId,
    eventType,
    payload: parsed,
    env: {
      cwd: (parsed.cwd as string | undefined) ?? process.cwd(),
      cliVersion,
      osPlatform: platform(),
      ...(repository
        ? {
            repoRoot: repository.repoRoot,
            repoKey: repository.repoKey,
            gitRoot: repository.repoRoot,
            repoFullName: repository.repoFullName,
            repoSyncId: repository.repoSyncId,
          }
        : {}),
      ...(workspaceId ? { workspaceId } : {}),
    },
    envelopeVersion: AGENT_ENVELOPE_VERSION,
    producer: agent,
    ...(invocationId ? { invocationId } : {}),
  };
}

export type CommitInfo = {
  sha: string;
  parentSha?: string;
  branch?: string;
  files: string[];
  filesComplete: boolean;
};

export type CommitAttribution = {
  sessionId: string;
  producer: Exclude<AgentProducer, "hermes">;
};

export type CommitMoveContext = {
  repository?: RepositoryContext | null;
  repoFullName?: string;
  /** Existing local `prim.repoSyncId`; never generated by the hook. */
  repoSyncId?: string;
  workspaceId?: string;
  attribution?: CommitAttribution;
};

const MAX_CLASSIFIER_ID_CHARS = 256;
// Keep client hints within the durable classifier's identifier contract.
// biome-ignore lint/suspicious/noControlCharactersInRegex: classifier hints reject controls and surrogate code units
const INVALID_CLASSIFIER_ID_RE = /[\u0000-\u001f\u007f\uD800-\uDFFF]/u;

function validSessionHint(value: string | undefined): value is string {
  return (
    typeof value === "string" &&
    value.trim().length > 0 &&
    value === value.trim() &&
    value.length <= MAX_CLASSIFIER_ID_CHARS &&
    !INVALID_CLASSIFIER_ID_RE.test(value)
  );
}

/**
 * Attribute a commit only when one supported agent exported exactly one valid
 * session hint and this worktree has a valid local identity. All other cases
 * deliberately stay sessionless for server-side evidence correlation.
 */
export function commitAttributionFromEnvironment(
  env: NodeJS.ProcessEnv,
  workspaceId: string | undefined,
): CommitAttribution | undefined {
  // Hermes commits are always correlated from server-stamped edit evidence.
  // Fail closed if its runtime inherited another agent's session variable.
  if (env.HERMES_INTERACTIVE) return undefined;
  if (!workspaceId || !isCanonicalWorkspaceId(workspaceId)) return undefined;
  const candidates = [
    validSessionHint(env.CLAUDE_CODE_SESSION_ID)
      ? { sessionId: env.CLAUDE_CODE_SESSION_ID, producer: "claude_code" as const }
      : undefined,
    validSessionHint(env.CODEX_THREAD_ID)
      ? { sessionId: env.CODEX_THREAD_ID, producer: "codex" as const }
      : undefined,
  ].filter((candidate): candidate is CommitAttribution => candidate !== undefined);
  return candidates.length === 1 ? candidates[0] : undefined;
}

/**
 * Build the Move a git post-commit hook emits. The commit bounds a
 * classification window server-side. When repository and worktree identities
 * are valid, its deterministic `commit:v2:<hash>` moveId makes a double-fired
 * or replayed hook idempotent without colliding with the same SHA in another
 * tenant or checkout. An identity-less fallback is random rather than global.
 * eventType "git.commit" matches the server's
 * GIT_COMMIT_EVENT — a cross-repo wire contract. No producer is stamped: a
 * git hook fires for every commit regardless of which agent (if any) was
 * running, and the decision's agent attribution comes from the session's
 * own moves, not the commit envelope. A uniquely attributable Claude/Codex
 * commit uses V3; human, GUI, Hermes, missing, or conflicting hints remain V1.
 */
export function toCommitMove(
  commit: CommitInfo,
  cliVersion: string,
  cwd: string,
  context: CommitMoveContext = {},
): Move {
  const { repository, repoFullName, repoSyncId, workspaceId, attribution } = context;
  const validatedRepoSyncId = isValidRepoSyncId(repoSyncId) ? repoSyncId : undefined;
  const validatedWorkspaceId =
    workspaceId && isCanonicalWorkspaceId(workspaceId) ? workspaceId : undefined;
  const validatedAttribution = validatedWorkspaceId ? attribution : undefined;
  const fullSha = /^(?:[0-9a-f]{40}|[0-9a-f]{64})$/u.test(commit.sha);
  const moveId =
    validatedRepoSyncId && validatedWorkspaceId && fullSha
      ? `commit:v2:${createHash("sha256")
          .update(
            JSON.stringify(["commit:v2", validatedRepoSyncId, validatedWorkspaceId, commit.sha]),
          )
          .digest("hex")}`
      : `commit:v2:unscoped:${randomUUID()}`;
  const base = {
    moveId,
    capturedAt: Date.now(),
    sessionId: validatedAttribution?.sessionId ?? "",
    eventType: "git.commit",
    payload: {
      kind: "git.commit",
      sha: commit.sha,
      parentSha: commit.parentSha,
      branch: commit.branch,
      changedFiles: commit.files,
      changedFilesComplete: commit.filesComplete,
    },
    env: {
      cwd,
      cliVersion,
      osPlatform: platform(),
      ...(repository
        ? {
            repoRoot: repository.repoRoot,
            repoKey: repository.repoKey,
            gitRoot: repository.repoRoot,
          }
        : {}),
      ...(repoFullName ? { repoFullName } : {}),
      ...(validatedRepoSyncId ? { repoSyncId: validatedRepoSyncId } : {}),
      ...(validatedWorkspaceId ? { workspaceId: validatedWorkspaceId } : {}),
    },
  };
  return validatedAttribution
    ? {
        ...base,
        envelopeVersion: AGENT_ENVELOPE_VERSION,
        producer: validatedAttribution.producer,
      }
    : { ...base, envelopeVersion: ENVELOPE_VERSION };
}

/**
 * Session-terminal events at which the hook kicks a best-effort background
 * drain, so a session's moves reach the server promptly instead of waiting
 * for the next interactive `prim` invocation.
 */
export function shouldFlushAfter(eventType: string): boolean {
  return eventType === "SessionEnd";
}
